/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'propertyType' : IDL.Text,
  'bedrooms' : IDL.Nat,
  'area' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'badge' : IDL.Opt(IDL.Text),
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'avatarUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'searchProperties' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'propertyType' : IDL.Text,
    'bedrooms' : IDL.Nat,
    'area' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'badge' : IDL.Opt(IDL.Text),
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'searchProperties' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };